/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    name: string;
    estimatedPortions: bigint;
    approvedPortions?: bigint;
    category: string;
    isManuallyEdited: boolean;
}
export type Time = bigint;
export interface Event {
    id: bigint;
    status: EventStatus;
    dietaryRequirements: Array<DietaryRequirement>;
    mainCourse: bigint;
    batchStrategies: Array<BatchStrategy>;
    desserts: bigint;
    alerts: Array<string>;
    temperature: bigint;
    vegStarters: bigint;
    date: Time;
    menuSuggestions: Array<MenuItem>;
    guestCount: bigint;
    nonVegStarters: bigint;
    name: string;
    kidPercentage: bigint;
    cuisinePreference: CuisinePreference;
    adultPercentage: bigint;
    approvedMenu: Array<MenuItem>;
    menuDescription: string;
    weather: Weather;
    drinks: bigint;
    location: string;
    mealTime: MealTime;
    eventType: EventType;
}
export interface BatchStrategy {
    triggerCondition: string;
    dishCategory: string;
    batch3Quantity: bigint;
    batch2Timing: string;
    batch2Quantity: bigint;
    dishName: string;
    batch1Quantity: bigint;
    batch1StartTime: string;
    cookingTimingSuggestion: string;
    riskLevel: RiskLevel;
    riskScore: bigint;
    totalPortions: bigint;
    adjustmentStrategy: string;
}
export enum CuisinePreference {
    continental = "continental",
    southIndian = "southIndian",
    northIndian = "northIndian",
    chinese = "chinese"
}
export enum DietaryRequirement {
    vegan = "vegan",
    glutenFree = "glutenFree",
    jain = "jain"
}
export enum EventStatus {
    completed = "completed",
    planned = "planned",
    cooking = "cooking"
}
export enum EventType {
    schoolFunction = "schoolFunction",
    wedding = "wedding",
    birthday = "birthday",
    corporate = "corporate"
}
export enum MealTime {
    lunch = "lunch",
    dinner = "dinner"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Weather {
    cloudy = "cloudy",
    sunny = "sunny",
    rainy = "rainy"
}
export interface backendInterface {
    addAlert(eventId: bigint, alert: string): Promise<void>;
    adjustBatchQuantities(eventId: bigint, dishName: string, adjustmentType: string): Promise<BatchStrategy>;
    calculateBatchStrategies(eventId: bigint): Promise<Array<BatchStrategy>>;
    createEvent(name: string, location: string, date: Time, guestCount: bigint, adultPercentage: bigint, kidPercentage: bigint, mealTime: MealTime, weather: Weather, temperature: bigint, menuDescription: string, vegStarters: bigint, nonVegStarters: bigint, mainCourse: bigint, desserts: bigint, drinks: bigint, eventType: EventType, cuisinePreference: CuisinePreference, dietaryRequirements: Array<DietaryRequirement>): Promise<bigint>;
    generateMenuSuggestions(eventId: bigint): Promise<Array<MenuItem>>;
    getEventDashboard(eventId: bigint): Promise<{
        id: bigint;
        status: EventStatus;
        dietaryRequirements: Array<DietaryRequirement>;
        mainCourse: bigint;
        batchStrategies: Array<BatchStrategy>;
        desserts: bigint;
        alerts: Array<string>;
        temperature: bigint;
        vegStarters: bigint;
        date: bigint;
        menuSuggestions: Array<MenuItem>;
        guestCount: bigint;
        nonVegStarters: bigint;
        name: string;
        kidPercentage: bigint;
        cuisinePreference: CuisinePreference;
        adultPercentage: bigint;
        approvedMenu: Array<MenuItem>;
        menuDescription: string;
        weather: Weather;
        drinks: bigint;
        location: string;
        mealTime: MealTime;
        eventType: EventType;
    }>;
    listEvents(): Promise<Array<Event>>;
    saveApprovedMenu(eventId: bigint, approvedMenu: Array<MenuItem>): Promise<void>;
    updateEventStatus(eventId: bigint, status: EventStatus): Promise<void>;
}
import type { BatchStrategy as _BatchStrategy, CuisinePreference as _CuisinePreference, DietaryRequirement as _DietaryRequirement, Event as _Event, EventStatus as _EventStatus, EventType as _EventType, MealTime as _MealTime, MenuItem as _MenuItem, RiskLevel as _RiskLevel, Time as _Time, Weather as _Weather } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAlert(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(arg0, arg1);
            return result;
        }
    }
    async adjustBatchQuantities(arg0: bigint, arg1: string, arg2: string): Promise<BatchStrategy> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustBatchQuantities(arg0, arg1, arg2);
                return from_candid_BatchStrategy_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustBatchQuantities(arg0, arg1, arg2);
            return from_candid_BatchStrategy_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async calculateBatchStrategies(arg0: bigint): Promise<Array<BatchStrategy>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateBatchStrategies(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateBatchStrategies(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: Time, arg3: bigint, arg4: bigint, arg5: bigint, arg6: MealTime, arg7: Weather, arg8: bigint, arg9: string, arg10: bigint, arg11: bigint, arg12: bigint, arg13: bigint, arg14: bigint, arg15: EventType, arg16: CuisinePreference, arg17: Array<DietaryRequirement>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_MealTime_n6(this._uploadFile, this._downloadFile, arg6), to_candid_Weather_n8(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11, arg12, arg13, arg14, to_candid_EventType_n10(this._uploadFile, this._downloadFile, arg15), to_candid_CuisinePreference_n12(this._uploadFile, this._downloadFile, arg16), to_candid_vec_n14(this._uploadFile, this._downloadFile, arg17));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_MealTime_n6(this._uploadFile, this._downloadFile, arg6), to_candid_Weather_n8(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11, arg12, arg13, arg14, to_candid_EventType_n10(this._uploadFile, this._downloadFile, arg15), to_candid_CuisinePreference_n12(this._uploadFile, this._downloadFile, arg16), to_candid_vec_n14(this._uploadFile, this._downloadFile, arg17));
            return result;
        }
    }
    async generateMenuSuggestions(arg0: bigint): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMenuSuggestions(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMenuSuggestions(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventDashboard(arg0: bigint): Promise<{
        id: bigint;
        status: EventStatus;
        dietaryRequirements: Array<DietaryRequirement>;
        mainCourse: bigint;
        batchStrategies: Array<BatchStrategy>;
        desserts: bigint;
        alerts: Array<string>;
        temperature: bigint;
        vegStarters: bigint;
        date: bigint;
        menuSuggestions: Array<MenuItem>;
        guestCount: bigint;
        nonVegStarters: bigint;
        name: string;
        kidPercentage: bigint;
        cuisinePreference: CuisinePreference;
        adultPercentage: bigint;
        approvedMenu: Array<MenuItem>;
        menuDescription: string;
        weather: Weather;
        drinks: bigint;
        location: string;
        mealTime: MealTime;
        eventType: EventType;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventDashboard(arg0);
                return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventDashboard(arg0);
            return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveApprovedMenu(arg0: bigint, arg1: Array<MenuItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveApprovedMenu(arg0, to_candid_vec_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveApprovedMenu(arg0, to_candid_vec_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEventStatus(arg0: bigint, arg1: EventStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEventStatus(arg0, to_candid_EventStatus_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEventStatus(arg0, to_candid_EventStatus_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BatchStrategy_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchStrategy): BatchStrategy {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_CuisinePreference_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CuisinePreference): CuisinePreference {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DietaryRequirement_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietaryRequirement): DietaryRequirement {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_MealTime_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealTime): MealTime {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Weather_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Weather): Weather {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    estimatedPortions: bigint;
    approvedPortions: [] | [bigint];
    category: string;
    isManuallyEdited: boolean;
}): {
    name: string;
    estimatedPortions: bigint;
    approvedPortions?: bigint;
    category: string;
    isManuallyEdited: boolean;
} {
    return {
        name: value.name,
        estimatedPortions: value.estimatedPortions,
        approvedPortions: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.approvedPortions)),
        category: value.category,
        isManuallyEdited: value.isManuallyEdited
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    triggerCondition: string;
    dishCategory: string;
    batch3Quantity: bigint;
    batch2Timing: string;
    batch2Quantity: bigint;
    dishName: string;
    batch1Quantity: bigint;
    batch1StartTime: string;
    cookingTimingSuggestion: string;
    riskLevel: _RiskLevel;
    riskScore: bigint;
    totalPortions: bigint;
    adjustmentStrategy: string;
}): {
    triggerCondition: string;
    dishCategory: string;
    batch3Quantity: bigint;
    batch2Timing: string;
    batch2Quantity: bigint;
    dishName: string;
    batch1Quantity: bigint;
    batch1StartTime: string;
    cookingTimingSuggestion: string;
    riskLevel: RiskLevel;
    riskScore: bigint;
    totalPortions: bigint;
    adjustmentStrategy: string;
} {
    return {
        triggerCondition: value.triggerCondition,
        dishCategory: value.dishCategory,
        batch3Quantity: value.batch3Quantity,
        batch2Timing: value.batch2Timing,
        batch2Quantity: value.batch2Quantity,
        dishName: value.dishName,
        batch1Quantity: value.batch1Quantity,
        batch1StartTime: value.batch1StartTime,
        cookingTimingSuggestion: value.cookingTimingSuggestion,
        riskLevel: from_candid_RiskLevel_n3(_uploadFile, _downloadFile, value.riskLevel),
        riskScore: value.riskScore,
        totalPortions: value.totalPortions,
        adjustmentStrategy: value.adjustmentStrategy
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EventStatus;
    dietaryRequirements: Array<_DietaryRequirement>;
    mainCourse: bigint;
    batchStrategies: Array<_BatchStrategy>;
    desserts: bigint;
    alerts: Array<string>;
    temperature: bigint;
    vegStarters: bigint;
    date: bigint;
    menuSuggestions: Array<_MenuItem>;
    guestCount: bigint;
    nonVegStarters: bigint;
    name: string;
    kidPercentage: bigint;
    cuisinePreference: _CuisinePreference;
    adultPercentage: bigint;
    approvedMenu: Array<_MenuItem>;
    menuDescription: string;
    weather: _Weather;
    drinks: bigint;
    location: string;
    mealTime: _MealTime;
    eventType: _EventType;
}): {
    id: bigint;
    status: EventStatus;
    dietaryRequirements: Array<DietaryRequirement>;
    mainCourse: bigint;
    batchStrategies: Array<BatchStrategy>;
    desserts: bigint;
    alerts: Array<string>;
    temperature: bigint;
    vegStarters: bigint;
    date: bigint;
    menuSuggestions: Array<MenuItem>;
    guestCount: bigint;
    nonVegStarters: bigint;
    name: string;
    kidPercentage: bigint;
    cuisinePreference: CuisinePreference;
    adultPercentage: bigint;
    approvedMenu: Array<MenuItem>;
    menuDescription: string;
    weather: Weather;
    drinks: bigint;
    location: string;
    mealTime: MealTime;
    eventType: EventType;
} {
    return {
        id: value.id,
        status: from_candid_EventStatus_n22(_uploadFile, _downloadFile, value.status),
        dietaryRequirements: from_candid_vec_n24(_uploadFile, _downloadFile, value.dietaryRequirements),
        mainCourse: value.mainCourse,
        batchStrategies: from_candid_vec_n5(_uploadFile, _downloadFile, value.batchStrategies),
        desserts: value.desserts,
        alerts: value.alerts,
        temperature: value.temperature,
        vegStarters: value.vegStarters,
        date: value.date,
        menuSuggestions: from_candid_vec_n17(_uploadFile, _downloadFile, value.menuSuggestions),
        guestCount: value.guestCount,
        nonVegStarters: value.nonVegStarters,
        name: value.name,
        kidPercentage: value.kidPercentage,
        cuisinePreference: from_candid_CuisinePreference_n27(_uploadFile, _downloadFile, value.cuisinePreference),
        adultPercentage: value.adultPercentage,
        approvedMenu: from_candid_vec_n17(_uploadFile, _downloadFile, value.approvedMenu),
        menuDescription: value.menuDescription,
        weather: from_candid_Weather_n29(_uploadFile, _downloadFile, value.weather),
        drinks: value.drinks,
        location: value.location,
        mealTime: from_candid_MealTime_n31(_uploadFile, _downloadFile, value.mealTime),
        eventType: from_candid_EventType_n33(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EventStatus;
    dietaryRequirements: Array<_DietaryRequirement>;
    mainCourse: bigint;
    batchStrategies: Array<_BatchStrategy>;
    desserts: bigint;
    alerts: Array<string>;
    temperature: bigint;
    vegStarters: bigint;
    date: _Time;
    menuSuggestions: Array<_MenuItem>;
    guestCount: bigint;
    nonVegStarters: bigint;
    name: string;
    kidPercentage: bigint;
    cuisinePreference: _CuisinePreference;
    adultPercentage: bigint;
    approvedMenu: Array<_MenuItem>;
    menuDescription: string;
    weather: _Weather;
    drinks: bigint;
    location: string;
    mealTime: _MealTime;
    eventType: _EventType;
}): {
    id: bigint;
    status: EventStatus;
    dietaryRequirements: Array<DietaryRequirement>;
    mainCourse: bigint;
    batchStrategies: Array<BatchStrategy>;
    desserts: bigint;
    alerts: Array<string>;
    temperature: bigint;
    vegStarters: bigint;
    date: Time;
    menuSuggestions: Array<MenuItem>;
    guestCount: bigint;
    nonVegStarters: bigint;
    name: string;
    kidPercentage: bigint;
    cuisinePreference: CuisinePreference;
    adultPercentage: bigint;
    approvedMenu: Array<MenuItem>;
    menuDescription: string;
    weather: Weather;
    drinks: bigint;
    location: string;
    mealTime: MealTime;
    eventType: EventType;
} {
    return {
        id: value.id,
        status: from_candid_EventStatus_n22(_uploadFile, _downloadFile, value.status),
        dietaryRequirements: from_candid_vec_n24(_uploadFile, _downloadFile, value.dietaryRequirements),
        mainCourse: value.mainCourse,
        batchStrategies: from_candid_vec_n5(_uploadFile, _downloadFile, value.batchStrategies),
        desserts: value.desserts,
        alerts: value.alerts,
        temperature: value.temperature,
        vegStarters: value.vegStarters,
        date: value.date,
        menuSuggestions: from_candid_vec_n17(_uploadFile, _downloadFile, value.menuSuggestions),
        guestCount: value.guestCount,
        nonVegStarters: value.nonVegStarters,
        name: value.name,
        kidPercentage: value.kidPercentage,
        cuisinePreference: from_candid_CuisinePreference_n27(_uploadFile, _downloadFile, value.cuisinePreference),
        adultPercentage: value.adultPercentage,
        approvedMenu: from_candid_vec_n17(_uploadFile, _downloadFile, value.approvedMenu),
        menuDescription: value.menuDescription,
        weather: from_candid_Weather_n29(_uploadFile, _downloadFile, value.weather),
        drinks: value.drinks,
        location: value.location,
        mealTime: from_candid_MealTime_n31(_uploadFile, _downloadFile, value.mealTime),
        eventType: from_candid_EventType_n33(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    planned: null;
} | {
    cooking: null;
}): EventStatus {
    return "completed" in value ? EventStatus.completed : "planned" in value ? EventStatus.planned : "cooking" in value ? EventStatus.cooking : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vegan: null;
} | {
    glutenFree: null;
} | {
    jain: null;
}): DietaryRequirement {
    return "vegan" in value ? DietaryRequirement.vegan : "glutenFree" in value ? DietaryRequirement.glutenFree : "jain" in value ? DietaryRequirement.jain : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    continental: null;
} | {
    southIndian: null;
} | {
    northIndian: null;
} | {
    chinese: null;
}): CuisinePreference {
    return "continental" in value ? CuisinePreference.continental : "southIndian" in value ? CuisinePreference.southIndian : "northIndian" in value ? CuisinePreference.northIndian : "chinese" in value ? CuisinePreference.chinese : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cloudy: null;
} | {
    sunny: null;
} | {
    rainy: null;
}): Weather {
    return "cloudy" in value ? Weather.cloudy : "sunny" in value ? Weather.sunny : "rainy" in value ? Weather.rainy : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lunch: null;
} | {
    dinner: null;
}): MealTime {
    return "lunch" in value ? MealTime.lunch : "dinner" in value ? MealTime.dinner : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    schoolFunction: null;
} | {
    wedding: null;
} | {
    birthday: null;
} | {
    corporate: null;
}): EventType {
    return "schoolFunction" in value ? EventType.schoolFunction : "wedding" in value ? EventType.wedding : "birthday" in value ? EventType.birthday : "corporate" in value ? EventType.corporate : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietaryRequirement>): Array<DietaryRequirement> {
    return value.map((x)=>from_candid_DietaryRequirement_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BatchStrategy>): Array<BatchStrategy> {
    return value.map((x)=>from_candid_BatchStrategy_n1(_uploadFile, _downloadFile, x));
}
function to_candid_CuisinePreference_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CuisinePreference): _CuisinePreference {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_DietaryRequirement_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryRequirement): _DietaryRequirement {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_EventStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): _EventStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_EventType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MealTime_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealTime): _MealTime {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItem_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_Weather_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Weather): _Weather {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    estimatedPortions: bigint;
    approvedPortions?: bigint;
    category: string;
    isManuallyEdited: boolean;
}): {
    name: string;
    estimatedPortions: bigint;
    approvedPortions: [] | [bigint];
    category: string;
    isManuallyEdited: boolean;
} {
    return {
        name: value.name,
        estimatedPortions: value.estimatedPortions,
        approvedPortions: value.approvedPortions ? candid_some(value.approvedPortions) : candid_none(),
        category: value.category,
        isManuallyEdited: value.isManuallyEdited
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    schoolFunction: null;
} | {
    wedding: null;
} | {
    birthday: null;
} | {
    corporate: null;
} {
    return value == EventType.schoolFunction ? {
        schoolFunction: null
    } : value == EventType.wedding ? {
        wedding: null
    } : value == EventType.birthday ? {
        birthday: null
    } : value == EventType.corporate ? {
        corporate: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CuisinePreference): {
    continental: null;
} | {
    southIndian: null;
} | {
    northIndian: null;
} | {
    chinese: null;
} {
    return value == CuisinePreference.continental ? {
        continental: null
    } : value == CuisinePreference.southIndian ? {
        southIndian: null
    } : value == CuisinePreference.northIndian ? {
        northIndian: null
    } : value == CuisinePreference.chinese ? {
        chinese: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryRequirement): {
    vegan: null;
} | {
    glutenFree: null;
} | {
    jain: null;
} {
    return value == DietaryRequirement.vegan ? {
        vegan: null
    } : value == DietaryRequirement.glutenFree ? {
        glutenFree: null
    } : value == DietaryRequirement.jain ? {
        jain: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): {
    completed: null;
} | {
    planned: null;
} | {
    cooking: null;
} {
    return value == EventStatus.completed ? {
        completed: null
    } : value == EventStatus.planned ? {
        planned: null
    } : value == EventStatus.cooking ? {
        cooking: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealTime): {
    lunch: null;
} | {
    dinner: null;
} {
    return value == MealTime.lunch ? {
        lunch: null
    } : value == MealTime.dinner ? {
        dinner: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Weather): {
    cloudy: null;
} | {
    sunny: null;
} | {
    rainy: null;
} {
    return value == Weather.cloudy ? {
        cloudy: null
    } : value == Weather.sunny ? {
        sunny: null
    } : value == Weather.rainy ? {
        rainy: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DietaryRequirement>): Array<_DietaryRequirement> {
    return value.map((x)=>to_candid_DietaryRequirement_n15(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MenuItem>): Array<_MenuItem> {
    return value.map((x)=>to_candid_MenuItem_n39(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
