/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const BatchStrategy = IDL.Record({
  'triggerCondition' : IDL.Text,
  'dishCategory' : IDL.Text,
  'batch3Quantity' : IDL.Nat,
  'batch2Timing' : IDL.Text,
  'batch2Quantity' : IDL.Nat,
  'dishName' : IDL.Text,
  'batch1Quantity' : IDL.Nat,
  'batch1StartTime' : IDL.Text,
  'cookingTimingSuggestion' : IDL.Text,
  'riskLevel' : RiskLevel,
  'riskScore' : IDL.Nat,
  'totalPortions' : IDL.Nat,
  'adjustmentStrategy' : IDL.Text,
});
export const Time = IDL.Int;
export const MealTime = IDL.Variant({
  'lunch' : IDL.Null,
  'dinner' : IDL.Null,
});
export const Weather = IDL.Variant({
  'cloudy' : IDL.Null,
  'sunny' : IDL.Null,
  'rainy' : IDL.Null,
});
export const EventType = IDL.Variant({
  'schoolFunction' : IDL.Null,
  'wedding' : IDL.Null,
  'birthday' : IDL.Null,
  'corporate' : IDL.Null,
});
export const CuisinePreference = IDL.Variant({
  'continental' : IDL.Null,
  'southIndian' : IDL.Null,
  'northIndian' : IDL.Null,
  'chinese' : IDL.Null,
});
export const DietaryRequirement = IDL.Variant({
  'vegan' : IDL.Null,
  'glutenFree' : IDL.Null,
  'jain' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'estimatedPortions' : IDL.Nat,
  'approvedPortions' : IDL.Opt(IDL.Nat),
  'category' : IDL.Text,
  'isManuallyEdited' : IDL.Bool,
});
export const EventStatus = IDL.Variant({
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'cooking' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : EventStatus,
  'dietaryRequirements' : IDL.Vec(DietaryRequirement),
  'mainCourse' : IDL.Nat,
  'batchStrategies' : IDL.Vec(BatchStrategy),
  'desserts' : IDL.Nat,
  'alerts' : IDL.Vec(IDL.Text),
  'temperature' : IDL.Int,
  'vegStarters' : IDL.Nat,
  'date' : Time,
  'menuSuggestions' : IDL.Vec(MenuItem),
  'guestCount' : IDL.Nat,
  'nonVegStarters' : IDL.Nat,
  'name' : IDL.Text,
  'kidPercentage' : IDL.Nat,
  'cuisinePreference' : CuisinePreference,
  'adultPercentage' : IDL.Nat,
  'approvedMenu' : IDL.Vec(MenuItem),
  'menuDescription' : IDL.Text,
  'weather' : Weather,
  'drinks' : IDL.Nat,
  'location' : IDL.Text,
  'mealTime' : MealTime,
  'eventType' : EventType,
});

export const idlService = IDL.Service({
  'addAlert' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adjustBatchQuantities' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [BatchStrategy],
      [],
    ),
  'calculateBatchStrategies' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BatchStrategy)],
      [],
    ),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        MealTime,
        Weather,
        IDL.Int,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        EventType,
        CuisinePreference,
        IDL.Vec(DietaryRequirement),
      ],
      [IDL.Nat],
      [],
    ),
  'generateMenuSuggestions' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], []),
  'getEventDashboard' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'id' : IDL.Nat,
          'status' : EventStatus,
          'dietaryRequirements' : IDL.Vec(DietaryRequirement),
          'mainCourse' : IDL.Nat,
          'batchStrategies' : IDL.Vec(BatchStrategy),
          'desserts' : IDL.Nat,
          'alerts' : IDL.Vec(IDL.Text),
          'temperature' : IDL.Int,
          'vegStarters' : IDL.Nat,
          'date' : IDL.Int,
          'menuSuggestions' : IDL.Vec(MenuItem),
          'guestCount' : IDL.Nat,
          'nonVegStarters' : IDL.Nat,
          'name' : IDL.Text,
          'kidPercentage' : IDL.Nat,
          'cuisinePreference' : CuisinePreference,
          'adultPercentage' : IDL.Nat,
          'approvedMenu' : IDL.Vec(MenuItem),
          'menuDescription' : IDL.Text,
          'weather' : Weather,
          'drinks' : IDL.Nat,
          'location' : IDL.Text,
          'mealTime' : MealTime,
          'eventType' : EventType,
        }),
      ],
      ['query'],
    ),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'saveApprovedMenu' : IDL.Func([IDL.Nat, IDL.Vec(MenuItem)], [], []),
  'updateEventStatus' : IDL.Func([IDL.Nat, EventStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const BatchStrategy = IDL.Record({
    'triggerCondition' : IDL.Text,
    'dishCategory' : IDL.Text,
    'batch3Quantity' : IDL.Nat,
    'batch2Timing' : IDL.Text,
    'batch2Quantity' : IDL.Nat,
    'dishName' : IDL.Text,
    'batch1Quantity' : IDL.Nat,
    'batch1StartTime' : IDL.Text,
    'cookingTimingSuggestion' : IDL.Text,
    'riskLevel' : RiskLevel,
    'riskScore' : IDL.Nat,
    'totalPortions' : IDL.Nat,
    'adjustmentStrategy' : IDL.Text,
  });
  const Time = IDL.Int;
  const MealTime = IDL.Variant({ 'lunch' : IDL.Null, 'dinner' : IDL.Null });
  const Weather = IDL.Variant({
    'cloudy' : IDL.Null,
    'sunny' : IDL.Null,
    'rainy' : IDL.Null,
  });
  const EventType = IDL.Variant({
    'schoolFunction' : IDL.Null,
    'wedding' : IDL.Null,
    'birthday' : IDL.Null,
    'corporate' : IDL.Null,
  });
  const CuisinePreference = IDL.Variant({
    'continental' : IDL.Null,
    'southIndian' : IDL.Null,
    'northIndian' : IDL.Null,
    'chinese' : IDL.Null,
  });
  const DietaryRequirement = IDL.Variant({
    'vegan' : IDL.Null,
    'glutenFree' : IDL.Null,
    'jain' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'estimatedPortions' : IDL.Nat,
    'approvedPortions' : IDL.Opt(IDL.Nat),
    'category' : IDL.Text,
    'isManuallyEdited' : IDL.Bool,
  });
  const EventStatus = IDL.Variant({
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'cooking' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : EventStatus,
    'dietaryRequirements' : IDL.Vec(DietaryRequirement),
    'mainCourse' : IDL.Nat,
    'batchStrategies' : IDL.Vec(BatchStrategy),
    'desserts' : IDL.Nat,
    'alerts' : IDL.Vec(IDL.Text),
    'temperature' : IDL.Int,
    'vegStarters' : IDL.Nat,
    'date' : Time,
    'menuSuggestions' : IDL.Vec(MenuItem),
    'guestCount' : IDL.Nat,
    'nonVegStarters' : IDL.Nat,
    'name' : IDL.Text,
    'kidPercentage' : IDL.Nat,
    'cuisinePreference' : CuisinePreference,
    'adultPercentage' : IDL.Nat,
    'approvedMenu' : IDL.Vec(MenuItem),
    'menuDescription' : IDL.Text,
    'weather' : Weather,
    'drinks' : IDL.Nat,
    'location' : IDL.Text,
    'mealTime' : MealTime,
    'eventType' : EventType,
  });
  
  return IDL.Service({
    'addAlert' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adjustBatchQuantities' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [BatchStrategy],
        [],
      ),
    'calculateBatchStrategies' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BatchStrategy)],
        [],
      ),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          MealTime,
          Weather,
          IDL.Int,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          EventType,
          CuisinePreference,
          IDL.Vec(DietaryRequirement),
        ],
        [IDL.Nat],
        [],
      ),
    'generateMenuSuggestions' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], []),
    'getEventDashboard' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'id' : IDL.Nat,
            'status' : EventStatus,
            'dietaryRequirements' : IDL.Vec(DietaryRequirement),
            'mainCourse' : IDL.Nat,
            'batchStrategies' : IDL.Vec(BatchStrategy),
            'desserts' : IDL.Nat,
            'alerts' : IDL.Vec(IDL.Text),
            'temperature' : IDL.Int,
            'vegStarters' : IDL.Nat,
            'date' : IDL.Int,
            'menuSuggestions' : IDL.Vec(MenuItem),
            'guestCount' : IDL.Nat,
            'nonVegStarters' : IDL.Nat,
            'name' : IDL.Text,
            'kidPercentage' : IDL.Nat,
            'cuisinePreference' : CuisinePreference,
            'adultPercentage' : IDL.Nat,
            'approvedMenu' : IDL.Vec(MenuItem),
            'menuDescription' : IDL.Text,
            'weather' : Weather,
            'drinks' : IDL.Nat,
            'location' : IDL.Text,
            'mealTime' : MealTime,
            'eventType' : EventType,
          }),
        ],
        ['query'],
      ),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'saveApprovedMenu' : IDL.Func([IDL.Nat, IDL.Vec(MenuItem)], [], []),
    'updateEventStatus' : IDL.Func([IDL.Nat, EventStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };