/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BatchStrategy {
  'triggerCondition' : string,
  'dishCategory' : string,
  'batch3Quantity' : bigint,
  'batch2Timing' : string,
  'batch2Quantity' : bigint,
  'dishName' : string,
  'batch1Quantity' : bigint,
  'batch1StartTime' : string,
  'cookingTimingSuggestion' : string,
  'riskLevel' : RiskLevel,
  'riskScore' : bigint,
  'totalPortions' : bigint,
  'adjustmentStrategy' : string,
}
export type CuisinePreference = { 'continental' : null } |
  { 'southIndian' : null } |
  { 'northIndian' : null } |
  { 'chinese' : null };
export type DietaryRequirement = { 'vegan' : null } |
  { 'glutenFree' : null } |
  { 'jain' : null };
export interface Event {
  'id' : bigint,
  'status' : EventStatus,
  'dietaryRequirements' : Array<DietaryRequirement>,
  'mainCourse' : bigint,
  'batchStrategies' : Array<BatchStrategy>,
  'desserts' : bigint,
  'alerts' : Array<string>,
  'temperature' : bigint,
  'vegStarters' : bigint,
  'date' : Time,
  'menuSuggestions' : Array<MenuItem>,
  'guestCount' : bigint,
  'nonVegStarters' : bigint,
  'name' : string,
  'kidPercentage' : bigint,
  'cuisinePreference' : CuisinePreference,
  'adultPercentage' : bigint,
  'approvedMenu' : Array<MenuItem>,
  'menuDescription' : string,
  'weather' : Weather,
  'drinks' : bigint,
  'location' : string,
  'mealTime' : MealTime,
  'eventType' : EventType,
}
export type EventStatus = { 'completed' : null } |
  { 'planned' : null } |
  { 'cooking' : null };
export type EventType = { 'schoolFunction' : null } |
  { 'wedding' : null } |
  { 'birthday' : null } |
  { 'corporate' : null };
export type MealTime = { 'lunch' : null } |
  { 'dinner' : null };
export interface MenuItem {
  'name' : string,
  'estimatedPortions' : bigint,
  'approvedPortions' : [] | [bigint],
  'category' : string,
  'isManuallyEdited' : boolean,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Time = bigint;
export type Weather = { 'cloudy' : null } |
  { 'sunny' : null } |
  { 'rainy' : null };
export interface _SERVICE {
  'addAlert' : ActorMethod<[bigint, string], undefined>,
  'adjustBatchQuantities' : ActorMethod<
    [bigint, string, string],
    BatchStrategy
  >,
  'calculateBatchStrategies' : ActorMethod<[bigint], Array<BatchStrategy>>,
  'createEvent' : ActorMethod<
    [
      string,
      string,
      Time,
      bigint,
      bigint,
      bigint,
      MealTime,
      Weather,
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      EventType,
      CuisinePreference,
      Array<DietaryRequirement>,
    ],
    bigint
  >,
  'generateMenuSuggestions' : ActorMethod<[bigint], Array<MenuItem>>,
  'getEventDashboard' : ActorMethod<
    [bigint],
    {
      'id' : bigint,
      'status' : EventStatus,
      'dietaryRequirements' : Array<DietaryRequirement>,
      'mainCourse' : bigint,
      'batchStrategies' : Array<BatchStrategy>,
      'desserts' : bigint,
      'alerts' : Array<string>,
      'temperature' : bigint,
      'vegStarters' : bigint,
      'date' : bigint,
      'menuSuggestions' : Array<MenuItem>,
      'guestCount' : bigint,
      'nonVegStarters' : bigint,
      'name' : string,
      'kidPercentage' : bigint,
      'cuisinePreference' : CuisinePreference,
      'adultPercentage' : bigint,
      'approvedMenu' : Array<MenuItem>,
      'menuDescription' : string,
      'weather' : Weather,
      'drinks' : bigint,
      'location' : string,
      'mealTime' : MealTime,
      'eventType' : EventType,
    }
  >,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'saveApprovedMenu' : ActorMethod<[bigint, Array<MenuItem>], undefined>,
  'updateEventStatus' : ActorMethod<[bigint, EventStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];